$Username = "BBimages"
$Password = "brodimgs"
$RemoteFile = "ftp://images.alphabroder.com/Hi-Res%20Web%20Images/"
#$ftpCreds = Get-Credential

$secpasswd = ConvertTo-SecureString $Password -AsPlainText -Force
$ftpCreds = New-Object System.Management.Automation.PSCredential($Username, $secpasswd)

Copy-Item "W:\ALPHA BRODER\PNGS\LAT\3523\3523_31.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\LAT\3523\3523_sd_31.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\LAT\3523\3523_bk_31.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\LAT\3532\3532_cg.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\LAT\3532\3532_sd_cg.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\LAT\3532\3532_bk_cg.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\LAT\3534\3534_21.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\LAT\3534\3534_sd_21.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\LAT\3534\3534_bk_21.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\LAT\3534\3534_c0.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\LAT\3534\3534_sd_c0.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\LAT\3534\3534_bk_c0.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\LAT\3534\3534_c1.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\LAT\3534\3534_sd_c1.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\LAT\3534\3534_bk_c1.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\LAT\3534\3534_C3.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\LAT\3534\3534_sd_c3.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\LAT\3534\3534_bk_c3.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\LAT\3534\3534_c4.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\LAT\3534\3534_sd_c4.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\LAT\3534\3534_bk_c4.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\LAT\3534\3534_c6.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\LAT\3534\3534_sd_c6.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\LAT\3534\3534_bk_c6.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\LAT\3534\3534_c7.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\LAT\3534\3534_sd_c7.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\LAT\3534\3534_bk_c7.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\LAT\3537\3537_BA.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\LAT\3537\3537_sd_ba.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\LAT\3537\3537_bk_ba.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\LAT\3537\3537_bv.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\LAT\3537\3537_sd_bv.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\LAT\3537\3537_bk_bv.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\LAT\3537\3537_bw.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\LAT\3537\3537_sd_bw.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\LAT\3537\3537_bk_bw.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\LAT\3537\3537_bx.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\LAT\3537\3537_sd_bx.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\LAT\3537\3537_bk_bx.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\LAT\3537\3537_bY.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\LAT\3537\3537_sd_by.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\LAT\3537\3537_bk_by.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\LAT\3537\3537_bz.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\LAT\3537\3537_sd_bz.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\LAT\3537\3537_bk_bz.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\LAT\3537\3537_ca.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\LAT\3537\3537_sd_ca.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\LAT\3537\3537_bk_ca.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\LAT\3537\3537_cg.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\LAT\3537\3537_sd_cg.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\LAT\3537\3537_bk_cg.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\NEXT LEVEL\3604\3604_30.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\NEXT LEVEL\3604\3604_sd_30.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\NEXT LEVEL\3604\3604_bk_30.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\NEXT LEVEL\6051\6051_ar.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\NEXT LEVEL\6051\6051_sd_ar.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\NEXT LEVEL\6051\6051_bk_ar.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\NEXT LEVEL\6051\6051_ba.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\NEXT LEVEL\6051\6051_sd_ba.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\NEXT LEVEL\6051\6051_bk_ba.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\LAT\6130\6130_85.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\LAT\6130\6130_sd_85.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\LAT\6130\6130_bk_85.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\LAT\6130\6130_86.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\LAT\6130\6130_sd_86.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\LAT\6130\6130_bk_86.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\LAT\6130\6130_a4.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\LAT\6130\6130_sd_a4.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\LAT\6130\6130_bk_a4.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\LAT\6130\6130_ad.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\LAT\6130\6130_sd_ad.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\LAT\6130\6130_bk_ad.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\LAT\6130\6130_af.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\LAT\6130\6130_sd_af.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\LAT\6130\6130_bk_af.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\LAT\6130\6130_ak.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\LAT\6130\6130_sd_ak.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\LAT\6130\6130_bk_ak.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\LAT\6130\6130_ci.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\LAT\6130\6130_sd_ci.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\LAT\6130\6130_bk_ci.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\LAT\6132\6132_cg.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\LAT\6132\6132_sd_cg.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\LAT\6132\6132_bk_cg.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\LAT\6137\6137_ba.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\LAT\6137\6137_sd_ba.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\LAT\6137\6137_bk_ba.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\LAT\6137\6137_bv.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\LAT\6137\6137_sd_bv.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\LAT\6137\6137_bk_bv.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\LAT\6137\6137_bw.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\LAT\6137\6137_sd_bw.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\LAT\6137\6137_bk_bw.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\LAT\6137\6137_bx.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\LAT\6137\6137_sd_bx.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\LAT\6137\6137_bk_bx.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\LAT\6137\6137_by.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\LAT\6137\6137_sd_by.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\LAT\6137\6137_bk_by.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\LAT\6137\6137_bz.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\LAT\6137\6137_sd_bz.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\LAT\6137\6137_bk_bz.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\LAT\6137\6137_ca.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\LAT\6137\6137_sd_ca.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\LAT\6137\6137_bk_ca.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\LAT\6137\6137_cg.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\LAT\6137\6137_sd_cg.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\LAT\6137\6137_bk_cg.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\NEXT LEVEL\6200\6200_19.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\NEXT LEVEL\6200\6200_sd_19.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\NEXT LEVEL\6200\6200_bk_19.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\NEXT LEVEL\6251\6251_04.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\NEXT LEVEL\6251\6251_sd_04.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\NEXT LEVEL\6251\6251_bk_04.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\NEXT LEVEL\6251\6251_36.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\NEXT LEVEL\6251\6251_sd_36.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\NEXT LEVEL\6251\6251_bk_36.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\NEXT LEVEL\6251\6251_41.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\NEXT LEVEL\6251\6251_sd_41.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\NEXT LEVEL\6251\6251_bk_41.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\NEXT LEVEL\6251\6251_51.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\NEXT LEVEL\6251\6251_sd_51.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\NEXT LEVEL\6251\6251_bk_51.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\NEXT LEVEL\6251\6251_sd_52.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\NEXT LEVEL\6251\6251_bk_52.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\NEXT LEVEL\6251\6251_53.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\NEXT LEVEL\6251\6251_sd_53.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\NEXT LEVEL\6251\6251_bk_53.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\NEXT LEVEL\6251\6251_57.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\NEXT LEVEL\6251\6251_sd_57.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\NEXT LEVEL\6251\6251_bk_57.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\NEXT LEVEL\6251\6251_ax.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\NEXT LEVEL\6251\6251_sd_ax.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\NEXT LEVEL\6251\6251_bk_ax.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\NEXT LEVEL\6251\6251_cp.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\NEXT LEVEL\6251\6251_sd_cp.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\NEXT LEVEL\6251\6251_cs.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\NEXT LEVEL\6251\6251_sd_cs.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\NEXT LEVEL\6251\6251_bk_cs.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\NEXT LEVEL\6251\6251_cv.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\NEXT LEVEL\6251\6251_sd_cv.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\NEXT LEVEL\6251\6251_bk_cv.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\NEXT LEVEL\6407\6407_cr.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\NEXT LEVEL\6407\6407_sd_cr.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\NEXT LEVEL\6407\6407_bk_cr.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\NEXT LEVEL\6407\6407_ct.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\NEXT LEVEL\6407\6407_sd_ct.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\NEXT LEVEL\6407\6407_bk_ct.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\NEXT LEVEL\6407\6407_cu.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\NEXT LEVEL\6407\6407_sd_cu.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\NEXT LEVEL\6407\6407_bk_cu.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\NEXT LEVEL\6407\6407_cx.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\NEXT LEVEL\6407\6407_sd_cx.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\NEXT LEVEL\6407\6407_bk_cx.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\NEXT LEVEL\6410\6410_bn.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\NEXT LEVEL\6410\6410_sd_bn.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\NEXT LEVEL\6410\6410_bk_bn.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\LAT\6901\6901_bg.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\LAT\6901\6901_sd_bg.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\LAT\6901\6901_bk_bg.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\LAT\6917\6917_19.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\LAT\6917\6917_sd_19.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\LAT\6917\6917_bk_19.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\LAT\6917\6917_20.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\LAT\6917\6917_sd_20.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\LAT\6917\6917_bk_20.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\LAT\6917\6917_63.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\LAT\6917\6917_sd_63.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\LAT\6917\6917_bk_63.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\LAT\6919\6919_57.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\LAT\6919\6919_sd_57.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\LAT\6919\6919_bk_57.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\LAT\6919\6919_98.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\LAT\6919\6919_sd_98.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\LAT\6919\6919_bk_98.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\LAT\6919\6919_b9.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\LAT\6919\6919_sd_b9.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\LAT\6919\6919_bk_b9.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\LAT\6930\6930_a4.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\LAT\6930\6930_sd_a4.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\LAT\6930\6930_bk_a4.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\LAT\6930\6930_bu.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\LAT\6930\6930_sd_bu.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\LAT\6930\6930_bk_bu.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\LAT\6930\6930_ci.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\LAT\6930\6930_sd_ci.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\LAT\6930\6930_bk_ci.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\LAT\6932\6932_cg.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\LAT\6932\6932_sd_cg.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\LAT\6932\6932_bk_cg.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\LAT\6934\6934_c1.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\LAT\6934\6934_sd_c1.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\LAT\6934\6934_bk_c1.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\LAT\6934\6934_c3.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\LAT\6934\6934_sd_c3.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\LAT\6934\6934_bk_c3.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\LAT\6934\6934_c4.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\LAT\6934\6934_sd_c4.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\LAT\6934\6934_bk_c4.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\LAT\6934\6934_c7.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\LAT\6934\6934_sd_c7.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\LAT\6934\6934_bk_c7.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\LAT\6937\6937_bz.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\LAT\6937\6937_sd_bz.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\LAT\6937\6937_bk_bz.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\LAT\6937\6937_cg.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\LAT\6937\6937_sd_cg.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\LAT\6937\6937_bk_cg.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\NEXT LEVEL\8221\8221_aj.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\NEXT LEVEL\8221\8221_sd_aj.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\NEXT LEVEL\8221\8221_bk_aj.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\NEXT LEVEL\8221\8221_cj.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\NEXT LEVEL\8221\8221_sd_cj.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\NEXT LEVEL\8221\8221_bk_cj.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\NEXT LEVEL\9301\9301_b4.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\NEXT LEVEL\9301\9301_sd_b4.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\NEXT LEVEL\9301\9301_bk_b4.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\NEXT LEVEL\9301\9301_b5.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\NEXT LEVEL\9301\9301_sd_b5.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\NEXT LEVEL\9301\9301_bk_b5.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\NEXT LEVEL\9601\9601_58.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\NEXT LEVEL\9601\9601_sd_58.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\NEXT LEVEL\9601\9601_bk_58.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\NEXT LEVEL\9601\9601_as.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\NEXT LEVEL\9601\9601_sd_as.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\NEXT LEVEL\9601\9601_bk_as.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\NEXT LEVEL\9601\9601_ay.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\NEXT LEVEL\9601\9601_sd_ay.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\NEXT LEVEL\9601\9601_bk_ay.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\ECONSCIOUS\EC1000\EC1000_AB.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\ECONSCIOUS\EC1000\EC1000_sd_AB.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\ECONSCIOUS\EC1000\EC1000_bk_AB.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\ECONSCIOUS\EC1000\EC1000_AC.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\ECONSCIOUS\EC1000\EC1000_sd_AC.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\ECONSCIOUS\EC1000\EC1000_bk_AC.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\ECONSCIOUS\EC1000\EC1000_AD.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\ECONSCIOUS\EC1000\EC1000_sd_AD.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\ECONSCIOUS\EC1000\EC1000_bk_AD.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\ECONSCIOUS\EC1075\ec1075_15.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\ECONSCIOUS\EC1075\ec1075_sd_15.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\ECONSCIOUS\EC1075\ec1075_bk_15.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\ECONSCIOUS\EC1085\EC1085_29.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\ECONSCIOUS\EC1085\EC1085_sd_29.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\ECONSCIOUS\EC1085\EC1085_bk_29.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\ECONSCIOUS\EC1085\EC1085_33.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\ECONSCIOUS\EC1085\EC1085_sd_33.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\ECONSCIOUS\EC1085\EC1085_bk_33.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\ECONSCIOUS\EC1085\EC1085_34.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\ECONSCIOUS\EC1085\EC1085_sd_34.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\ECONSCIOUS\EC1085\EC1085_bk_34.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\ECONSCIOUS\EC1085\EC1085_36.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\ECONSCIOUS\EC1085\EC1085_sd_36.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\ECONSCIOUS\EC1085\EC1085_bk_36.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\ECONSCIOUS\EC1085\EC1085_37.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\ECONSCIOUS\EC1085\EC1085_sd_37.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\ECONSCIOUS\EC1085\EC1085_bk_37.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\ECONSCIOUS\EC1588\ec1588_29.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\ECONSCIOUS\EC1588\ec1588_sd_29.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\ECONSCIOUS\EC1588\ec1588_bk_29.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\ECONSCIOUS\EC1588\ec1588_34.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\ECONSCIOUS\EC1588\ec1588_sd_34.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\ECONSCIOUS\EC1588\ec1588_bk_34.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\ECONSCIOUS\EC1588\ec1588_36.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\ECONSCIOUS\EC1588\ec1588_sd_36.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\ECONSCIOUS\EC1588\ec1588_bk_36.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\ECONSCIOUS\EC2505\EC2505_00.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\ECONSCIOUS\EC2505\EC2505_sd_00.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\ECONSCIOUS\EC2505\EC2505_bk_00.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\ECONSCIOUS\EC4501\EC4501_02.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\ECONSCIOUS\EC4501\EC4501_SD_02.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\ECONSCIOUS\EC4501\EC4501_BK_02.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\ECONSCIOUS\EC4501\EC4501_AH.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\ECONSCIOUS\EC4501\EC4501_SD_AH.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\ECONSCIOUS\EC4501\EC4501_BK_AH.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\ECONSCIOUS\EC4505\EC4505_29.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\ECONSCIOUS\EC4505\EC4505_sd_29.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\ECONSCIOUS\EC4505\EC4505_bk_29.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\ECONSCIOUS\EC4505\EC4505_34.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\ECONSCIOUS\EC4505\EC4505_sd_34.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\ECONSCIOUS\EC4505\EC4505_bk_34.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\ECONSCIOUS\EC4505\EC4505_36.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\ECONSCIOUS\EC4505\EC4505_sd_36.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\ECONSCIOUS\EC4505\EC4505_bk_36.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\ECONSCIOUS\EC4505\EC4505_86.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\ECONSCIOUS\EC4505\EC4505_sd_86.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\ECONSCIOUS\EC4505\EC4505_bk_86.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Invoke-WebRequest -Uri "ftp://images.alphabroder.com/Hi-Res%20Web%20Images/ja8912_bk_60_p.jpg" -OutFile "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - RAW\ja8912_bk_60_p.jpg" -Credential $ftpCreds
Invoke-WebRequest -Uri "ftp://images.alphabroder.com/Hi-Res%20Web%20Images/ja8912_bk_65_p.jpg" -OutFile "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - RAW\ja8912_bk_65_p.jpg" -Credential $ftpCreds
Invoke-WebRequest -Uri "ftp://images.alphabroder.com/Hi-Res%20Web%20Images/ja8912_bk_66_p.jpg" -OutFile "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - RAW\ja8912_bk_66_p.jpg" -Credential $ftpCreds
Invoke-WebRequest -Uri "ftp://images.alphabroder.com/Hi-Res%20Web%20Images/ja8912_bk_91_p.jpg" -OutFile "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - RAW\ja8912_bk_91_p.jpg" -Credential $ftpCreds
Invoke-WebRequest -Uri "ftp://images.alphabroder.com/Hi-Res%20Web%20Images/ja8916_bk_64_p.jpg" -OutFile "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - RAW\ja8916_bk_64_p.jpg" -Credential $ftpCreds
Invoke-WebRequest -Uri "ftp://images.alphabroder.com/Hi-Res%20Web%20Images/ja8916_bk_65_p.jpg" -OutFile "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - RAW\ja8916_bk_65_p.jpg" -Credential $ftpCreds
Copy-Item "W:\ALPHA BRODER\PNGS\LAT\LA3530\la3530_85.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\LAT\LA3530\la3530_sd_85.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\LAT\LA3530\la3530_bk_85.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\LAT\LA3530\la3530_86.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\LAT\LA3530\la3530_sd_86.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\LAT\LA3530\la3530_bk_86.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\LAT\LA3530\la3530_a4.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\LAT\LA3530\la3530_sd_a4.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\LAT\LA3530\la3530_bk_a4.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\LAT\LA3530\la3530_ad.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\LAT\LA3530\la3530_sd_ad.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\LAT\LA3530\la3530_bk_ad.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\LAT\LA3530\la3530_af.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\LAT\LA3530\la3530_sd_af.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\LAT\LA3530\la3530_bk_af.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\LAT\LA3530\la3530_ak.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\LAT\LA3530\la3530_sd_ak.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\LAT\LA3530\la3530_bk_ak.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\LAT\LA3530\la3530_bu.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\LAT\LA3530\la3530_sd_bu.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\LAT\LA3530\la3530_bk_bu.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\LAT\LA3533\la3533_am.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\LAT\LA3533\la3533_sd_am.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\LAT\LA3533\la3533_bk_am.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\LAT\LA3533\la3533_aw.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\LAT\LA3533\la3533_sd_aw.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\LAT\LA3533\la3533_bk_aw.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\LAT\LA3533\la3533_b0.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\LAT\LA3533\la3533_sd_b0.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\LAT\LA3533\la3533_bk_b0.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\LAT\LA3533\la3533_ce.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\LAT\LA3533\la3533_sd_ce.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\LAT\LA3533\la3533_bk_ce.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\LAT\LA3538\la3538_38.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\LAT\LA3538\la3538_sd_38.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\LAT\LA3538\la3538_bk_38.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\LAT\LA3538\la3538_bd.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\LAT\LA3538\la3538_sd_bd.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\LAT\LA3538\la3538_bk_bd.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\LAT\LA3538\la3538_bj.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\LAT\LA3538\la3538_sd_bj.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\LAT\LA3538\la3538_bk_bj.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\LAT\LA3538\la3538_bk.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\LAT\LA3538\la3538_sd_bk.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\LAT\LA3538\la3538_bk_bk.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\LAT\LA3538\la3538_bm.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\LAT\LA3538\la3538_sd_bm.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\LAT\LA3538\la3538_bk_bm.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\LAT\LA3538\la3538_bp.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\LAT\LA3538\la3538_sd_bp.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\LAT\LA3538\la3538_bk_bp.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\LAT\LA3538\la3538_bs.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\LAT\LA3538\la3538_sd_bs.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\LAT\LA3538\la3538_bk_bs.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\LAT\LA3538\la3538_d6.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\LAT\LA3538\la3538_sd_d6.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\LAT\LA3538\la3538_bk_d6.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\LAT\LA6911\la6911_57.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\LAT\LA6911\la6911_sd_57.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\LAT\LA6911\la6911_bk_57.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\LAT\LA6911\la6911_70.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\LAT\LA6911\la6911_sd_70.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\LAT\LA6911\la6911_bk_70.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\LAT\LA6911\la6911_a5.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\LAT\LA6911\la6911_sd_a5.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\LAT\LA6911\la6911_bk_a5.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\NEXT LEVEL\N1800\n1800_29.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\NEXT LEVEL\N1800\n1800_sd_29.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\NEXT LEVEL\N1800\n1800_bk_29.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\NEXT LEVEL\N1800\n1800_51.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\NEXT LEVEL\N1800\n1800_sd_51.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\NEXT LEVEL\N1800\n1800_bk_51.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\NEXT LEVEL\N6210\n6210_76.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\NEXT LEVEL\N6210\n6210_sd_76.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\NEXT LEVEL\N6210\n6210_bk_76.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\NEXT LEVEL\3533\3533_45.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\NEXT LEVEL\3533\3533_sd_45.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\NEXT LEVEL\3533\3533_bk_45.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\NEXT LEVEL\6410\6410_19.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\NEXT LEVEL\6410\6410_sd_19.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\NEXT LEVEL\6410\6410_bk_19.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\LAT\3523\3523_31.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\LAT\3523\3523_sd_31.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\LAT\3523\3523_bk_31.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\LAT\3532\3532_cg.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\LAT\3532\3532_sd_cg.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\LAT\3532\3532_bk_cg.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\LAT\3534\3534_21.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\LAT\3534\3534_sd_21.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\LAT\3534\3534_bk_21.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\LAT\3534\3534_c0.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\LAT\3534\3534_sd_c0.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\LAT\3534\3534_bk_c0.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\LAT\3534\3534_c1.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\LAT\3534\3534_sd_c1.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\LAT\3534\3534_bk_c1.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\LAT\3534\3534_C3.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\LAT\3534\3534_sd_c3.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\LAT\3534\3534_bk_c3.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\LAT\3534\3534_c4.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\LAT\3534\3534_sd_c4.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\LAT\3534\3534_bk_c4.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\LAT\3534\3534_c6.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\LAT\3534\3534_sd_c6.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\LAT\3534\3534_bk_c6.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\LAT\3534\3534_c7.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\LAT\3534\3534_sd_c7.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\LAT\3534\3534_bk_c7.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\LAT\3537\3537_BA.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\LAT\3537\3537_sd_ba.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\LAT\3537\3537_bk_ba.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\LAT\3537\3537_bv.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\LAT\3537\3537_sd_bv.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\LAT\3537\3537_bk_bv.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\LAT\3537\3537_bw.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\LAT\3537\3537_sd_bw.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\LAT\3537\3537_bk_bw.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\LAT\3537\3537_bx.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\LAT\3537\3537_sd_bx.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\LAT\3537\3537_bk_bx.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\LAT\3537\3537_bY.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\LAT\3537\3537_sd_by.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\LAT\3537\3537_bk_by.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\LAT\3537\3537_bz.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\LAT\3537\3537_sd_bz.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\LAT\3537\3537_bk_bz.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\LAT\3537\3537_ca.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\LAT\3537\3537_sd_ca.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\LAT\3537\3537_bk_ca.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\LAT\3537\3537_cg.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\LAT\3537\3537_sd_cg.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\LAT\3537\3537_bk_cg.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\NEXT LEVEL\3604\3604_30.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\NEXT LEVEL\3604\3604_sd_30.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\NEXT LEVEL\3604\3604_bk_30.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\NEXT LEVEL\6051\6051_ar.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\NEXT LEVEL\6051\6051_sd_ar.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\NEXT LEVEL\6051\6051_bk_ar.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\NEXT LEVEL\6051\6051_ba.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\NEXT LEVEL\6051\6051_sd_ba.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\NEXT LEVEL\6051\6051_bk_ba.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\LAT\6130\6130_85.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\LAT\6130\6130_sd_85.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\LAT\6130\6130_bk_85.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\LAT\6130\6130_86.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\LAT\6130\6130_sd_86.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\LAT\6130\6130_bk_86.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\LAT\6130\6130_a4.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\LAT\6130\6130_sd_a4.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\LAT\6130\6130_bk_a4.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\LAT\6130\6130_ad.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\LAT\6130\6130_sd_ad.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\LAT\6130\6130_bk_ad.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\LAT\6130\6130_af.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\LAT\6130\6130_sd_af.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\LAT\6130\6130_bk_af.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\LAT\6130\6130_ak.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\LAT\6130\6130_sd_ak.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\LAT\6130\6130_bk_ak.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\LAT\6130\6130_ci.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\LAT\6130\6130_sd_ci.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\LAT\6130\6130_bk_ci.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\LAT\6132\6132_cg.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\LAT\6132\6132_sd_cg.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\LAT\6132\6132_bk_cg.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\LAT\6137\6137_ba.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\LAT\6137\6137_sd_ba.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\LAT\6137\6137_bk_ba.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\LAT\6137\6137_bv.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\LAT\6137\6137_sd_bv.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\LAT\6137\6137_bk_bv.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\LAT\6137\6137_bw.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\LAT\6137\6137_sd_bw.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\LAT\6137\6137_bk_bw.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\LAT\6137\6137_bx.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\LAT\6137\6137_sd_bx.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\LAT\6137\6137_bk_bx.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\LAT\6137\6137_by.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\LAT\6137\6137_sd_by.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\LAT\6137\6137_bk_by.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\LAT\6137\6137_bz.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\LAT\6137\6137_sd_bz.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\LAT\6137\6137_bk_bz.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\LAT\6137\6137_ca.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\LAT\6137\6137_sd_ca.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\LAT\6137\6137_bk_ca.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\LAT\6137\6137_cg.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\LAT\6137\6137_sd_cg.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\LAT\6137\6137_bk_cg.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\NEXT LEVEL\6200\6200_19.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\NEXT LEVEL\6200\6200_sd_19.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\NEXT LEVEL\6200\6200_bk_19.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\NEXT LEVEL\6251\6251_04.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\NEXT LEVEL\6251\6251_sd_04.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\NEXT LEVEL\6251\6251_bk_04.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\NEXT LEVEL\6251\6251_36.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\NEXT LEVEL\6251\6251_sd_36.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\NEXT LEVEL\6251\6251_bk_36.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\NEXT LEVEL\6251\6251_41.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\NEXT LEVEL\6251\6251_sd_41.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\NEXT LEVEL\6251\6251_bk_41.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\NEXT LEVEL\6251\6251_51.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\NEXT LEVEL\6251\6251_sd_51.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\NEXT LEVEL\6251\6251_bk_51.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\NEXT LEVEL\6251\6251_sd_52.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\NEXT LEVEL\6251\6251_bk_52.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\NEXT LEVEL\6251\6251_53.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\NEXT LEVEL\6251\6251_sd_53.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\NEXT LEVEL\6251\6251_bk_53.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\NEXT LEVEL\6251\6251_57.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\NEXT LEVEL\6251\6251_sd_57.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\NEXT LEVEL\6251\6251_bk_57.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\NEXT LEVEL\6251\6251_ax.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\NEXT LEVEL\6251\6251_sd_ax.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\NEXT LEVEL\6251\6251_bk_ax.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\NEXT LEVEL\6251\6251_cp.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\NEXT LEVEL\6251\6251_sd_cp.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\NEXT LEVEL\6251\6251_cs.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\NEXT LEVEL\6251\6251_sd_cs.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\NEXT LEVEL\6251\6251_bk_cs.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\NEXT LEVEL\6251\6251_cv.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\NEXT LEVEL\6251\6251_sd_cv.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\NEXT LEVEL\6251\6251_bk_cv.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\NEXT LEVEL\6407\6407_cr.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\NEXT LEVEL\6407\6407_sd_cr.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\NEXT LEVEL\6407\6407_bk_cr.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\NEXT LEVEL\6407\6407_ct.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\NEXT LEVEL\6407\6407_sd_ct.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\NEXT LEVEL\6407\6407_bk_ct.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\NEXT LEVEL\6407\6407_cu.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\NEXT LEVEL\6407\6407_sd_cu.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\NEXT LEVEL\6407\6407_bk_cu.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\NEXT LEVEL\6407\6407_cx.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\NEXT LEVEL\6407\6407_sd_cx.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\NEXT LEVEL\6407\6407_bk_cx.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\NEXT LEVEL\6410\6410_bn.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\NEXT LEVEL\6410\6410_sd_bn.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\NEXT LEVEL\6410\6410_bk_bn.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\LAT\6901\6901_bg.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\LAT\6901\6901_sd_bg.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\LAT\6901\6901_bk_bg.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\LAT\6917\6917_19.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\LAT\6917\6917_sd_19.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\LAT\6917\6917_bk_19.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\LAT\6917\6917_20.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\LAT\6917\6917_sd_20.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\LAT\6917\6917_bk_20.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\LAT\6917\6917_63.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\LAT\6917\6917_sd_63.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\LAT\6917\6917_bk_63.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\LAT\6919\6919_57.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\LAT\6919\6919_sd_57.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\LAT\6919\6919_bk_57.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\LAT\6919\6919_98.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\LAT\6919\6919_sd_98.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\LAT\6919\6919_bk_98.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\LAT\6919\6919_b9.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\LAT\6919\6919_sd_b9.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\LAT\6919\6919_bk_b9.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\LAT\6930\6930_a4.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\LAT\6930\6930_sd_a4.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\LAT\6930\6930_bk_a4.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\LAT\6930\6930_bu.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\LAT\6930\6930_sd_bu.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\LAT\6930\6930_bk_bu.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\LAT\6930\6930_ci.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\LAT\6930\6930_sd_ci.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\LAT\6930\6930_bk_ci.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\LAT\6932\6932_cg.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\LAT\6932\6932_sd_cg.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\LAT\6932\6932_bk_cg.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\LAT\6934\6934_c1.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\LAT\6934\6934_sd_c1.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\LAT\6934\6934_bk_c1.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\LAT\6934\6934_c3.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\LAT\6934\6934_sd_c3.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\LAT\6934\6934_bk_c3.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\LAT\6934\6934_c4.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\LAT\6934\6934_sd_c4.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\LAT\6934\6934_bk_c4.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\LAT\6934\6934_c7.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\LAT\6934\6934_sd_c7.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\LAT\6934\6934_bk_c7.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\LAT\6937\6937_bz.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\LAT\6937\6937_sd_bz.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\LAT\6937\6937_bk_bz.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\LAT\6937\6937_cg.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\LAT\6937\6937_sd_cg.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\LAT\6937\6937_bk_cg.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\NEXT LEVEL\8221\8221_aj.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\NEXT LEVEL\8221\8221_sd_aj.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\NEXT LEVEL\8221\8221_bk_aj.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\NEXT LEVEL\8221\8221_cj.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\NEXT LEVEL\8221\8221_sd_cj.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\NEXT LEVEL\8221\8221_bk_cj.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\NEXT LEVEL\9301\9301_b4.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\NEXT LEVEL\9301\9301_sd_b4.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\NEXT LEVEL\9301\9301_bk_b4.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\NEXT LEVEL\9301\9301_b5.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\NEXT LEVEL\9301\9301_sd_b5.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\NEXT LEVEL\9301\9301_bk_b5.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\NEXT LEVEL\9601\9601_58.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\NEXT LEVEL\9601\9601_sd_58.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\NEXT LEVEL\9601\9601_bk_58.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\NEXT LEVEL\9601\9601_as.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\NEXT LEVEL\9601\9601_sd_as.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\NEXT LEVEL\9601\9601_bk_as.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\NEXT LEVEL\9601\9601_ay.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\NEXT LEVEL\9601\9601_sd_ay.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\NEXT LEVEL\9601\9601_bk_ay.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\ECONSCIOUS\EC1000\EC1000_AB.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\ECONSCIOUS\EC1000\EC1000_sd_AB.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\ECONSCIOUS\EC1000\EC1000_bk_AB.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\ECONSCIOUS\EC1000\EC1000_AC.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\ECONSCIOUS\EC1000\EC1000_sd_AC.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\ECONSCIOUS\EC1000\EC1000_bk_AC.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\ECONSCIOUS\EC1000\EC1000_AD.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\ECONSCIOUS\EC1000\EC1000_sd_AD.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\ECONSCIOUS\EC1000\EC1000_bk_AD.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\ECONSCIOUS\EC1075\ec1075_15.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\ECONSCIOUS\EC1075\ec1075_sd_15.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\ECONSCIOUS\EC1075\ec1075_bk_15.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\ECONSCIOUS\EC1085\EC1085_29.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\ECONSCIOUS\EC1085\EC1085_sd_29.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\ECONSCIOUS\EC1085\EC1085_bk_29.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\ECONSCIOUS\EC1085\EC1085_33.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\ECONSCIOUS\EC1085\EC1085_sd_33.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\ECONSCIOUS\EC1085\EC1085_bk_33.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\ECONSCIOUS\EC1085\EC1085_34.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\ECONSCIOUS\EC1085\EC1085_sd_34.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\ECONSCIOUS\EC1085\EC1085_bk_34.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\ECONSCIOUS\EC1085\EC1085_36.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\ECONSCIOUS\EC1085\EC1085_sd_36.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\ECONSCIOUS\EC1085\EC1085_bk_36.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\ECONSCIOUS\EC1085\EC1085_37.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\ECONSCIOUS\EC1085\EC1085_sd_37.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\ECONSCIOUS\EC1085\EC1085_bk_37.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\ECONSCIOUS\EC1588\ec1588_29.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\ECONSCIOUS\EC1588\ec1588_sd_29.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\ECONSCIOUS\EC1588\ec1588_bk_29.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\ECONSCIOUS\EC1588\ec1588_34.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\ECONSCIOUS\EC1588\ec1588_sd_34.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\ECONSCIOUS\EC1588\ec1588_bk_34.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\ECONSCIOUS\EC1588\ec1588_36.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\ECONSCIOUS\EC1588\ec1588_sd_36.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\ECONSCIOUS\EC1588\ec1588_bk_36.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\ECONSCIOUS\EC2505\EC2505_00.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\ECONSCIOUS\EC2505\EC2505_sd_00.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\ECONSCIOUS\EC2505\EC2505_bk_00.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\ECONSCIOUS\EC4501\EC4501_02.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\ECONSCIOUS\EC4501\EC4501_SD_02.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\ECONSCIOUS\EC4501\EC4501_BK_02.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\ECONSCIOUS\EC4501\EC4501_AH.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\ECONSCIOUS\EC4501\EC4501_SD_AH.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\ECONSCIOUS\EC4501\EC4501_BK_AH.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\ECONSCIOUS\EC4505\EC4505_29.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\ECONSCIOUS\EC4505\EC4505_sd_29.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\ECONSCIOUS\EC4505\EC4505_bk_29.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\ECONSCIOUS\EC4505\EC4505_34.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\ECONSCIOUS\EC4505\EC4505_sd_34.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\ECONSCIOUS\EC4505\EC4505_bk_34.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\ECONSCIOUS\EC4505\EC4505_36.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\ECONSCIOUS\EC4505\EC4505_sd_36.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\ECONSCIOUS\EC4505\EC4505_bk_36.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\ECONSCIOUS\EC4505\EC4505_86.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\ECONSCIOUS\EC4505\EC4505_sd_86.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\ECONSCIOUS\EC4505\EC4505_bk_86.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Invoke-WebRequest -Uri "ftp://images.alphabroder.com/Hi-Res%20Web%20Images/ja8912_bk_60_p.jpg" -OutFile "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - RAW\ja8912_bk_60_p.jpg" -Credential $ftpCreds
Invoke-WebRequest -Uri "ftp://images.alphabroder.com/Hi-Res%20Web%20Images/ja8912_bk_65_p.jpg" -OutFile "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - RAW\ja8912_bk_65_p.jpg" -Credential $ftpCreds
Invoke-WebRequest -Uri "ftp://images.alphabroder.com/Hi-Res%20Web%20Images/ja8912_bk_66_p.jpg" -OutFile "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - RAW\ja8912_bk_66_p.jpg" -Credential $ftpCreds
Invoke-WebRequest -Uri "ftp://images.alphabroder.com/Hi-Res%20Web%20Images/ja8912_bk_91_p.jpg" -OutFile "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - RAW\ja8912_bk_91_p.jpg" -Credential $ftpCreds
Invoke-WebRequest -Uri "ftp://images.alphabroder.com/Hi-Res%20Web%20Images/ja8916_bk_64_p.jpg" -OutFile "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - RAW\ja8916_bk_64_p.jpg" -Credential $ftpCreds
Invoke-WebRequest -Uri "ftp://images.alphabroder.com/Hi-Res%20Web%20Images/ja8916_bk_65_p.jpg" -OutFile "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - RAW\ja8916_bk_65_p.jpg" -Credential $ftpCreds
Copy-Item "W:\ALPHA BRODER\PNGS\LAT\LA3530\la3530_85.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\LAT\LA3530\la3530_sd_85.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\LAT\LA3530\la3530_bk_85.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\LAT\LA3530\la3530_86.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\LAT\LA3530\la3530_sd_86.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\LAT\LA3530\la3530_bk_86.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\LAT\LA3530\la3530_a4.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\LAT\LA3530\la3530_sd_a4.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\LAT\LA3530\la3530_bk_a4.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\LAT\LA3530\la3530_ad.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\LAT\LA3530\la3530_sd_ad.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\LAT\LA3530\la3530_bk_ad.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\LAT\LA3530\la3530_af.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\LAT\LA3530\la3530_sd_af.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\LAT\LA3530\la3530_bk_af.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\LAT\LA3530\la3530_ak.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\LAT\LA3530\la3530_sd_ak.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\LAT\LA3530\la3530_bk_ak.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\LAT\LA3530\la3530_bu.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\LAT\LA3530\la3530_sd_bu.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\LAT\LA3530\la3530_bk_bu.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\LAT\LA3533\la3533_am.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\LAT\LA3533\la3533_sd_am.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\LAT\LA3533\la3533_bk_am.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\LAT\LA3533\la3533_aw.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\LAT\LA3533\la3533_sd_aw.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\LAT\LA3533\la3533_bk_aw.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\LAT\LA3533\la3533_b0.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\LAT\LA3533\la3533_sd_b0.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\LAT\LA3533\la3533_bk_b0.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\LAT\LA3533\la3533_ce.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\LAT\LA3533\la3533_sd_ce.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\LAT\LA3533\la3533_bk_ce.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\LAT\LA3538\la3538_38.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\LAT\LA3538\la3538_sd_38.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\LAT\LA3538\la3538_bk_38.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\LAT\LA3538\la3538_bd.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\LAT\LA3538\la3538_sd_bd.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\LAT\LA3538\la3538_bk_bd.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\LAT\LA3538\la3538_bj.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\LAT\LA3538\la3538_sd_bj.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\LAT\LA3538\la3538_bk_bj.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\LAT\LA3538\la3538_bk.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\LAT\LA3538\la3538_sd_bk.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\LAT\LA3538\la3538_bk_bk.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\LAT\LA3538\la3538_bm.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\LAT\LA3538\la3538_sd_bm.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\LAT\LA3538\la3538_bk_bm.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\LAT\LA3538\la3538_bp.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\LAT\LA3538\la3538_sd_bp.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\LAT\LA3538\la3538_bk_bp.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\LAT\LA3538\la3538_bs.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\LAT\LA3538\la3538_sd_bs.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\LAT\LA3538\la3538_bk_bs.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\LAT\LA3538\la3538_d6.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\LAT\LA3538\la3538_sd_d6.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\LAT\LA3538\la3538_bk_d6.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\LAT\LA6911\la6911_57.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\LAT\LA6911\la6911_sd_57.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\LAT\LA6911\la6911_bk_57.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\LAT\LA6911\la6911_70.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\LAT\LA6911\la6911_sd_70.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\LAT\LA6911\la6911_bk_70.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\LAT\LA6911\la6911_a5.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\LAT\LA6911\la6911_sd_a5.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\LAT\LA6911\la6911_bk_a5.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\NEXT LEVEL\N1800\n1800_29.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\NEXT LEVEL\N1800\n1800_sd_29.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\NEXT LEVEL\N1800\n1800_bk_29.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\NEXT LEVEL\N1800\n1800_51.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\NEXT LEVEL\N1800\n1800_sd_51.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\NEXT LEVEL\N1800\n1800_bk_51.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\NEXT LEVEL\N6210\n6210_76.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\NEXT LEVEL\N6210\n6210_sd_76.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\NEXT LEVEL\N6210\n6210_bk_76.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\NEXT LEVEL\3533\3533_45.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\NEXT LEVEL\3533\3533_sd_45.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\NEXT LEVEL\3533\3533_bk_45.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\NEXT LEVEL\6410\6410_19.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\NEXT LEVEL\6410\6410_sd_19.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
Copy-Item "W:\ALPHA BRODER\PNGS\NEXT LEVEL\6410\6410_bk_19.png" "G:\Shared drives\SJC Alpha\Fashion Guide\IMAGES - PROCESSED\"
